name: Release Please

on:
    push:
        branches: [main]

jobs:
    # test:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v4

    #         - name: Setup pnpm
    #           uses: pnpm/action-setup@v4
    #           with:
    #               version: 9

    #         - name: Setup Node.js
    #           uses: actions/setup-node@v4
    #           with:
    #               node-version: 20
    #               cache: "pnpm"

    #         - name: Install dependencies
    #           run: pnpm install

    #         - name: Run tests
    #           run: pnpm test

    release-please:
        # needs: test
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Release Please
              id: release
              uses: google-github-actions/release-please-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  config-file: .github/release-please-config.json
                  manifest-file: .github/.release-please-manifest.json
